export const reviewsByRating = {
  5: [
    "Best optical shop in the area honestly. Eye test was thorough, frames are stylish and lenses are crystal clear!",
    "Optical Galaxy ne meri aankhon ki life badal di ekdum sahi prescription aur perfect fitting frames!",
    "Doctor sahab ne itne detail mein samjhaya ki pehli baar aankhon ki health sach mein samajh aayi!",
    "Screens ke wajah se aankhein thak jaati thi, blue light glasses liye yahan se ab bahut better feel hota hai!",
    "Mummy ke progressive lenses yahan se liye, doctor ne bahut patiently explain kiya outstanding service!",
    "Best place for eyeglasses in Delhi quality is top notch and staff never pushes you to buy expensive stuff!",
    "Came for a routine checkup and left genuinely impressed modern equipment, honest advice, great frames!",
    "Sabse pehle yahan aana chahiye tha sahi prescription, sahi frames, sahi price, sab kuch perfect!",
    "My entire family gets their glasses from here trust factor is 100%, quality never disappoints!",
    "Anti-glare coating yahan ki best hai raat ko driving itni easy ho gayi hai, highly recommended!",
    "Glasses 2 din mein ready ho gayi aur fit bhi ekdum perfect lightning fast service!",
    "Pehle kai jagah try kiya but Optical Galaxy ki lens clarity ka koi muqabla nahi!",
    "Staff suggested frames that actually suited my face felt like shopping with an honest friend!",
    "Power badh rahi thi bachpan se, yahan sahi guidance mili aur best quality lenses mile grateful!",
    "Office mein 10 ghante screen ke saamne baithta hoon, yahan ki computer glasses ne aankhon ko rescue kar liya!",
    "Ekdum genuine shop no gimmicks, no overcharging, just honest eye care and quality products!",
    "Got my contact lens fitting done here doctor was so thorough and patient, first time was smooth!",
    "Yahan ka collection dekh ke lagta hai har face shape ke liye frames hain loved every option!",
    "Doctor ne meri child ki aankhon ka test itni carefully kiya, aisi dedicated service bahut rare hai!",
    "Headaches band ho gaye naye glasses ke baad sahi prescription ka itna fark hota hai!",
    "Budget mein bhi itne achhe frames milte hain yahan, ek dum value for money experience!",
    "My prescription was complex but they handled it perfectly no compromise on quality whatsoever!",
    "Sunglasses with power bhi yahan milti hain, ek hi jagah sab solution Optical Galaxy rocks!",
    "Dadi ki aankhein weak ho rahi thi, yahan ke doctor ne itna carefully guide kiya truly grateful!",
    "Staff remembers your name and prescription iss level ki personalized service rarely milti hai!",
    "Titanium frames recommend kiye unhone lightweight, durable, best investment for my eyes!",
    "Har saal checkup ke liye yahan aata hoon, kabhi ek baar bhi disappoint nahi kiya Optical Galaxy ne!",
    "Lens toot gayi thi ek, same day replacement kar diya unhone amazing after-sales service!",
    "Kids ka frame collection bhi bahut cute aur durable hai mera beta rooz khushi se glasses pehanta hai!",
    "Eye flu ke baad sensitivity badh gayi thi, yahan sahi photochromic lens suggest kiya game changer!",
    "Neighbours ne recommend kiya tha, ab main bhi apne saare dosto ko recommend karta hoon simply the best!",
    "Got my glasses adjusted after 6 months for free yahi loyalty build karti hai ek shop ko!",
    "Cataract surgery ke baad ki special glasses yahan se li, doctor ne sab kuch patiently explain kiya!",
    "Honestly the most hygienic and well-maintained optical shop I've visited everything spotless!",
    "Meri naak pe frames sahi nahi baithte the, unhone nose pads adjust kiye bilkul free mein so helpful!",
    "Power -5 hai meri, thin lenses suggest kiye jo glasses ko light bhi rakhte hain perfect recommendation!",
    "Yahan aake lagta hai aankhon ki sahi care ho rahi hai not just selling glasses but genuine eye health!",
    "Best anti-scratch lenses mili hain yahan, 1 saal ho gaya abhi tak ek scratch nahi outstanding quality!",
    "Doctor ne diabetes mein aankhon ki care ke baare mein jo tips diye, woh gold hai truly knowledgeable!",
    "First time contact lens user thi, staff ne itne patience se guide kiya could not have asked for better!",
    "Frame ki warranty claim karna tha, bina koi argument ke replace kar diya best customer service!",
    "Husband aur main dono ke liye ek saath glasses banvayi, dono ekdum perfect efficient and reliable!",
    "Yahan ki UV protection sunglasses bahut achhi hain, aankhein summer mein comfortable rehti hain ab!",
    "Palak ke doctor ne referral diya tha Optical Galaxy ka, aur sach mein best decision tha aana yahan!",
    "Itni baar glasses banayi life mein, par yahan jitna satisfied kabhi nahi tha truly exceptional!",
    "Remote work ke baad aankhein bahut stress mein thi, yahan ka solution ekdum on point tha!",
    "Yahan glasses lena matlab quality guarantee 2 saal ho gaye abhi tak bilkul perfect condition mein!",
    "Explained the difference between CR39 and polycarbonate lenses so clearly so knowledgeable!",
    "My first glasses experience was here and they made it so comfortable will never go anywhere else!",
    "Ekdum transparent pricing koi hidden charges nahi, jo bola wahi liya, aisa honesty bohot kam milti hai!",
    "Very good experience at Optical Galaxy. Eye testing was done properly and the staff explaned everything very nicely. Got my glasses ready on time.",
    "Best optical shop in the area honestly. So many frame options and prices were also resonable.",
    "I got progressive glasses made from here and the comfort is amazing. No headche no adjustment issue.",
    "Eye testing machine looked very advanced and the optometrist checked my eyes patiently.",
    "Bought blue cut lenses for office work and my eyes feel much less strained now.",
    "Staff behaviour was very polite and friendly. They helped me choose frames according to my face shape.",
    "Nice collection of branded and normal frames both. Loved the varety.",
    "I got coloured lenses from here and the quality was really good.",
    "Service was quick and professional. Delivery was before expected date.",
    "Very neat and clean clinic. Felt comfortable throughout the visit.",
    "My number was changing frequently so I visited here for eye testing. They explaned everything in simple language.",
    "Affordable pricing with very premium quality lenses.",
    "I visited with my parents and everyone was satisifed with the service.",
    "The progressive lenses they suggsted are very comfortable for daily use.",
    "Genuine guidance was given instead of forcing expensive products.",
    "Highly satisfied with the fitting of my spectacles.",
    "Eye checkup was detailed and not rushed.",
    "One of the few places where customer service still matters.",
    "Frames are trendy and lightweight. Got many compliments after buying from here.",
    "Very professional setup. Felt like a proper eye clinic.",
    "Blue cut glasses quality is excellent. Perfect for students and office work.",
    "Their lens finishing work is very clean.",
    "Staff listned carefully to my requirements and suggested the perfect frame.",
    "Good experience from start to finish.",
    "I got glasses made for my child and the staff handled everything patiently.",
    "Prices are fair and service is reliable.",
    "They checked my eyesight properly and suggested the right power.",
    "The owner is very humble and helpful.",
    "Great collection of sunglasses and regular glasses both.",
    "Comfortable environment and very cooperative people.",
    "Lens quality is much better than my previous spectacles.",
    "Eye testing process was smooth and professional.",
    "Fast service and accurate fitting.",
    "Happy with the overall experience.",
    "They explained the differnce between different lenses very clearly.",
    "Nice experience for first time spectacle users.",
    "The glasses feel lightweight and comfortable even after long hours.",
    "They have options for every budget.",
    "Good quality frames at resonable prices.",
    "Optical Galaxy is now my permanent optical shop.",
    "Excellent after sales support also.",
    "The coloured contact lenses looked natural and comfortable.",
    "I was confused about progressive lenses but they guided me properly.",
    "Staff was patient even though I took time choosing frames.",
    "Very accurate eye testing.",
    "Nice behaviour and quality work.",
    "The frame fitting was perfect from day one.",
    "Got my spectacles repaired quickly also.",
    "Trusted place for eye care and glasses.",
    "Overall amazing experience. Definitely recommended.",
  ],
  4: [
    "Really good optical shop eye test was proper, frames selection is decent, overall happy with the visit!",
    "Achha experience raha, doctor knowledgeable the aur frames bhi reasonable price mein mile recommended!",
    "Good quality lenses and friendly staff slight wait time but the service was worth every minute!",
    "Meri prescription complicated thi, unhone handle kar liya bina kisi issue ke good professional service!",
    "Nice collection of frames, got mine in 3 days solid quality and fair pricing throughout!",
    "Eye test accurate tha aur staff helpful tha thoda aur variety frames mein ho toh aur perfect hoga!",
    "Contact lens consultation was very helpful doctor explained everything clearly and patiently!",
    "Good value for money quality lenses, decent frames, honest staff, would definitely return!",
    "Glasses ready before promised date always appreciate when a shop respects your time!",
    "Staff ne sahi lens coating recommend kiya jo mujhe pata bhi nahi tha knowledgeable team!",
    "Anti-reflective coating quality is very good night driving became much more comfortable after this!",
    "Yahan ka lens quality bahut achha hai, frame selection thodi aur variety ke saath aur better ho sakta tha!",
    "Smooth and professional experience eye test was detailed, no unnecessary upselling, happy customer!",
    "Good shop for all age groups from kids to elderly, they handle every case with care!",
    "Brought my parents here for senior eye care staff was respectful and very patient with them!",
    "Prompt service, accurate prescription, good frame quality ticking all the right boxes!",
    "Had a good experience overall doctor was thorough and lenses came out perfect, minor wait only!",
    "Replaced my broken frame under warranty without fuss good after-sales support here!",
    "Reasonable price for the quality you get better than many bigger branded optical stores in the city!",
    "Very cooperative staff, helped me choose between multiple frame styles patient and genuinely helpful!",
    "Good experience overall. Delivery took one extra day but quality was worth it.",
    "Nice collection of frames and lenses. Staff was helpful.",
    "Eye testing was done properly and glasses are comfortable.",
    "Prices are decent compared to other optical shops nearby.",
    "Blue cut lenses are really helping during screen time.",
    "Staff behaviour was polite and professional.",
    "Good variety in frames but I wish there were more colour options.",
    "Spectacles quality is very nice.",
    "Comfortable experience and proper guidance.",
    "Progressive lenses are working well for me.",
    "Clinic is clean and organized.",
    "Service was smooth from testing to delivery.",
    "Happy with the fitting and finishing.",
    "They explaned lens options clearly.",
    "Good place for eye testing.",
    "The owner was cooperative and friendly.",
    "Contact lens quality was good.",
    "I liked the frame collection.",
    "Glasses are lightweight and stylish.",
    "Proper eye checkup with modern machines.",
    "Good customer handling.",
    "Pricing is resonable for the quality.",
    "Nice experience for first time visitors.",
    "Delivery timing could improve slightly but overall good.",
    "Staff helped me choose a suitable frame.",
    "Happy with the lens clarity.",
    "Good balance of quality and price.",
    "Eye test felt detailed and accurate.",
    "They have many options for all age groups.",
    "Nice atmosphere and supportive staff.",
    "The glasses feel comfortable after long use.",
    "Lens quality is impressive.",
    "Got good suggesttions according to my budget.",
    "Reliable optical clinic.",
    "Frame fitting was good.",
    "Happy with the customer service.",
    "They solved my issue patiently.",
    "Nice shop for spectacles and lenses.",
    "Proper guidance without pressure.",
    "Overall a satisfying experience.",
    "Good for eye testing and glasses both.",
    "Staff explaned everything in simple words.",
    "Coloured lenses looked nice and natural.",
    "Comfortable glasses and good service.",
    "Nice collection for students and working people.",
    "The progressive glasses are easy to use.",
    "Good quality work.",
    "Spectacles were deliverd in proper condition.",
    "Helpful staff and fair pricing.",
    "Would visit again for future eye checkups.",
  ],
  3: [
    "Theek experience raha eye test ho gaya, glasses mil gayi, quality okay hai, nothing extraordinary!",
    "Average visit eye test was fine, frame selection is limited but got what I needed without any issues!",
    "Decent shop, staff polite but guidance could have been better when selecting lens type and coating!",
    "Got my glasses made here quality seems okay, took slightly longer than expected but no major complaints!",
    "Okay experience overall doctor was professional but the waiting area could be more comfortable!",
    "Glasses are fine, price was reasonable, service was average nothing to complain but nothing wow either!",
    "Staff was helpful but seemed busy could use more attention to each customer during peak hours!",
    "Prescription was accurate which is most important rest of the experience was fairly standard!",
    "Visited on a busy Saturday service was slower than usual but the final product was acceptable!",
    "Decent optical shop does the job, quality is okay, would try again on a less busy weekday!",
    "Experience was average but decent overall.",
    "Eye testing was good but waiting time was a little longer.",
    "Glasses quality is fine for the price.",
    "Staff was polite and helpful.",
    "Good collection but some frames were out of stock.",
    "Progressive lenses took some time to adjust to.",
    "Service was okay and delivery was on time.",
    "Clinic was clean and organized.",
    "Blue cut glasses are comfortable.",
    "Prices are resonable.",
    "Eye checkup felt professional.",
    "Frames are stylish but I expected more options.",
    "Overall decent experience.",
    "Lens clarity is satisfactory.",
    "Staff behaviour was good.",
    "Contact lenses quality is nice.",
    "The fitting needed minor adjustmet later.",
    "Good for regular eye testing.",
    "Delivery timing was average.",
    "Customer service was fine.",
    "The glasses are comfortable after adjustment.",
    "Good place for affordable frames.",
    "Eye test was done carefully.",
    "Staff answerd my questions properly.",
    "Decent quality and pricing.",
    "They guided me according to my needs.",
    "Progressive glasses are working okay now.",
    "Nice environment inside the clinic.",
    "Blue cut lenses are useful for laptop work.",
    "Collection is decent.",
    "Overall okay experience.",
    "Spectacle quality is acceptable.",
    "They helped me choose a better frame.",
    "Eye testing machines looked modern.",
    "Service was normal but satisfactory.",
    "Good support after purchase.",
    "Comfortable fitting after correction.",
    "Delivery was slightly delayed.",
    "Resonable pricing.",
    "Contact lenses were comfortable.",
    "Nice behaviour by the owner.",
    "Frames are lightweight.",
    "Eye testing process was smooth.",
    "Satisfied with the purchase overall.",
    "Good enough for routine eye care.",
    "Staff handled customers well.",
    "Decent optical shop.",
    "Lens quality is okay.",
    "They have many frame styles.",
    "Average but reliable experience.",
  ],
  2: [
    "Service was okay but delivery took longer than expected.",
    "Eye testing was fine but the shop was crowded.",
    "Frame collection is decent but limited in some styles.",
    "Glasses quality is average.",
    "Staff was polite but service felt slow.",
    "I expected faster response after placing the order.",
    "Progressive lenses took time to get comfortable.",
    "Eye checkup was decent. Overall an average experience.",
    "Blue cut lenses are fine but not a huge diffrence for me.",
    "Delivery was delayed by a few days.",
    "Fitting needed adjustmet later.",
    "Good behaviour by staff but service could improve.",
    "The glasses are fine now after correction.",
    "Waiting time was more than expected.",
    "Shop is clean and organized.",
    "Some frame options were unavailable.",
    "Lens quality is acceptable.",
    "The eye testing process felt rushed.",
    "Prices are manageable but not the cheapest.",
    "Service is average.",
    "Staff was cooperative.",
    "I expected more variety in frames.",
    "Delivery timing should improve.",
    "Eye checkup was satisfactory.",
    "The spectacles are okay for daily use.",
    "Customer support was decent.",
    "Progressive glasses needed readjustment.",
    "The clinic looked professional.",
    "Contact lenses were comfortable enough.",
    "The frame fitting was slightly loose intially.",
    "They solved the issue after visiting again.",
    "Average experience overall.",
    "Staff behaviour was respectful.",
    "Blue cut glasses quality is decent.",
    "I had to wait for service.",
    "Lens finishing could have been better.",
    "Good location and easy to find.",
    "Eye testing machines looked advanced.",
    "Some communication gap happened during order.",
    "The glasses are usable now.",
    "Prices are normal.",
    "Staff was patient with customers.",
    "Service needs slight improvement.",
    "Decent optical store.",
  ],
};