export const reviewsByRating = {
  5: [
    "Best optical shop in the area — eye test was thorough, frames are stylish, and lenses are crystal clear!",
    "Optical Galaxy ne meri aankhon ki life badal di — ekdum sahi prescription aur perfect fitting frames!",
    "Doctor sahab ne itne detail mein samjhaya ki pehli baar aankhon ki health sach mein samajh aayi!",
    "Screens ke wajah se aankhein thak jaati thi, blue light glasses liye yahan se — ab bahut better feel hota hai!",
    "Mummy ke progressive lenses yahan se liye, doctor ne bahut patiently explain kiya — outstanding service!",
    "Best place for eyeglasses in Delhi — quality is top notch and staff never pushes you to buy expensive stuff!",
    "Came for a routine checkup and left genuinely impressed — modern equipment, honest advice, great frames!",
    "Sabse pehle yahan aana chahiye tha — sahi prescription, sahi frames, sahi price, sab kuch perfect!",
    "My entire family gets their glasses from here — trust factor is 100%, quality never disappoints!",
    "Anti-glare coating yahan ki best hai — raat ko driving itni easy ho gayi hai, highly recommended!",
    "Glasses 2 din mein ready ho gayi aur fit bhi ekdum perfect — lightning fast service!",
    "Pehle kai jagah try kiya but Optical Galaxy ki lens clarity ka koi muqabla nahi!",
    "Staff suggested frames that actually suited my face — felt like shopping with an honest friend!",
    "Power badh rahi thi bachpan se, yahan sahi guidance mili aur best quality lenses mile — grateful!",
    "Office mein 10 ghante screen ke saamne baithta hoon, yahan ki computer glasses ne aankhon ko rescue kar liya!",
    "Ekdum genuine shop — no gimmicks, no overcharging, just honest eye care and quality products!",
    "Got my contact lens fitting done here — doctor was so thorough and patient, first time was smooth!",
    "Yahan ka collection dekh ke lagta hai har face shape ke liye frames hain — loved every option!",
    "Doctor ne meri child ki aankhon ka test itni carefully kiya, aisi dedicated service bahut rare hai!",
    "Headaches band ho gaye naye glasses ke baad — sahi prescription ka itna fark hota hai!",
    "Budget mein bhi itne achhe frames milte hain yahan, ek dum value for money experience!",
    "My prescription was complex but they handled it perfectly — no compromise on quality whatsoever!",
    "Sunglasses with power bhi yahan milti hain, ek hi jagah sab solution — Optical Galaxy rocks!",
    "Dadi ki aankhein weak ho rahi thi, yahan ke doctor ne itna carefully guide kiya — truly grateful!",
    "Staff remembers your name and prescription — iss level ki personalized service rarely milti hai!",
    "Titanium frames recommend kiye unhone — lightweight, durable, best investment for my eyes!",
    "Har saal checkup ke liye yahan aata hoon, kabhi ek baar bhi disappoint nahi kiya Optical Galaxy ne!",
    "Lens toot gayi thi ek, same day replacement kar diya unhone — amazing after-sales service!",
    "Kids ka frame collection bhi bahut cute aur durable hai — mera beta rooz khushi se glasses pehanta hai!",
    "Eye flu ke baad sensitivity badh gayi thi, yahan sahi photochromic lens suggest kiya — game changer!",
    "Neighbours ne recommend kiya tha, ab main bhi apne saare dosto ko recommend karta hoon — simply the best!",
    "Got my glasses adjusted after 6 months for free — yahi loyalty build karti hai ek shop ko!",
    "Cataract surgery ke baad ki special glasses yahan se li, doctor ne sab kuch patiently explain kiya!",
    "Honestly the most hygienic and well-maintained optical shop I've visited — everything spotless!",
    "Meri naak pe frames sahi nahi baithte the, unhone nose pads adjust kiye bilkul free mein — so helpful!",
    "Power -5 hai meri, thin lenses suggest kiye jo glasses ko light bhi rakhte hain — perfect recommendation!",
    "Yahan aake lagta hai aankhon ki sahi care ho rahi hai — not just selling glasses but genuine eye health!",
    "Best anti-scratch lenses mili hain yahan, 1 saal ho gaya abhi tak ek scratch nahi — outstanding quality!",
    "Doctor ne diabetes mein aankhon ki care ke baare mein jo tips diye, woh gold hai — truly knowledgeable!",
    "First time contact lens user thi, staff ne itne patience se guide kiya — could not have asked for better!",
    "Frame ki warranty claim karna tha, bina koi argument ke replace kar diya — best customer service!",
    "Husband aur main dono ke liye ek saath glasses banvayi, dono ekdum perfect — efficient and reliable!",
    "Yahan ki UV protection sunglasses bahut achhi hain, aankhein summer mein comfortable rehti hain ab!",
    "Palak ke doctor ne referral diya tha Optical Galaxy ka, aur sach mein best decision tha aana yahan!",
    "Itni baar glasses banayi life mein, par yahan jitna satisfied kabhi nahi tha — truly exceptional!",
    "Remote work ke baad aankhein bahut stress mein thi, yahan ka solution ekdum on point tha!",
    "Yahan glasses lena matlab quality guarantee — 2 saal ho gaye abhi tak bilkul perfect condition mein!",
    "Explained the difference between CR39 and polycarbonate lenses so clearly — so knowledgeable!",
    "My first glasses experience was here and they made it so comfortable — will never go anywhere else!",
    "Ekdum transparent pricing — koi hidden charges nahi, jo bola wahi liya, aisa honesty bohot kam milti hai!",
  ],
  4: [
    "Really good optical shop — eye test was proper, frames selection is decent, overall happy with the visit!",
    "Achha experience raha, doctor knowledgeable the aur frames bhi reasonable price mein mile — recommended!",
    "Good quality lenses and friendly staff — slight wait time but the service was worth every minute!",
    "Meri prescription complicated thi, unhone handle kar liya bina kisi issue ke — good professional service!",
    "Nice collection of frames, got mine in 3 days — solid quality and fair pricing throughout!",
    "Eye test accurate tha aur staff helpful tha — thoda aur variety frames mein ho toh aur perfect hoga!",
    "Contact lens consultation was very helpful — doctor explained everything clearly and patiently!",
    "Good value for money — quality lenses, decent frames, honest staff, would definitely return!",
    "Glasses ready before promised date — always appreciate when a shop respects your time!",
    "Staff ne sahi lens coating recommend kiya jo mujhe pata bhi nahi tha — knowledgeable team!",
    "Anti-reflective coating quality is very good — night driving became much more comfortable after this!",
    "Yahan ka lens quality bahut achha hai, frame selection thodi aur variety ke saath aur better ho sakta tha!",
    "Smooth and professional experience — eye test was detailed, no unnecessary upselling, happy customer!",
    "Good shop for all age groups — from kids to elderly, they handle every case with care!",
    "Brought my parents here for senior eye care — staff was respectful and very patient with them!",
    "Prompt service, accurate prescription, good frame quality — ticking all the right boxes for a 4-star!",
    "Had a good experience overall — doctor was thorough and lenses came out perfect, minor wait only!",
    "Replaced my broken frame under warranty without fuss — good after-sales support here!",
    "Reasonable price for the quality you get — better than many bigger branded optical stores in the city!",
    "Very cooperative staff, helped me choose between multiple frame styles — patient and genuinely helpful!",
  ],
  3: [
    "Theek experience raha — eye test ho gaya, glasses mil gayi, quality okay hai, nothing extraordinary!",
    "Average visit — eye test was fine, frame selection is limited but got what I needed without any issues!",
    "Decent shop, staff polite but guidance could have been better when selecting lens type and coating!",
    "Got my glasses made here — quality seems okay, took slightly longer than expected but no major complaints!",
    "Okay experience overall — doctor was professional but the waiting area could be more comfortable!",
    "Glasses are fine, price was reasonable, service was average — nothing to complain but nothing wow either!",
    "Staff was helpful but seemed busy — could use more attention to each customer during peak hours!",
    "Prescription was accurate which is most important — rest of the experience was fairly standard!",
    "Visited on a busy Saturday — service was slower than usual but the final product was acceptable!",
    "Decent optical shop — does the job, quality is okay, would try again on a less busy weekday!",
  ],
};